/* Libraries */
const BigNumber = require('bignumber.js')
const Web3 = require('web3')
const web3 = new Web3()

/* Contracts */
const MultiSigWallet = artifacts.require('MultiSigWallet.sol')
const SafeMathLib = artifacts.require('SafeMathLib.sol')
const CrowdsaleToken = artifacts.require('CrowdsaleToken.sol')
const MilestonePricing = artifacts.require('MilestonePricing.sol')
const CargoXCrowdsale = artifacts.require('CargoXCrowdsale.sol')
const BonusFinalizeAgent = artifacts.require('BonusFinalizeAgent.sol')

// NOTE: these are the first three addresses generated by the
// mnemonic defined in truffle.js. For production real addresses
// need to be specified.
const CX_MULTISIG_WALLET_OWNERS = [
  "0x6f9Fb8BE7758BAa1E40aEc36dAaAaf0D08dfd6A2",
  "0x523426947e88f45b756e7adc806E1E38BAeb2F3F",
  "0x0C8Ea0876ef4E29Fcb2428B5aA21d4761C92bbD4"
]
const CX_MULTISIG_WALLET_REQ_SIG = 2

const CX_TOKEN_NAME = "CargoX Token"
const CX_TOKEN_SYMBOL = "CXO"
const CX_TOKEN_INITIAL_SUPPLY = 0
const CX_TOKEN_DECIMALS = 18

const CX_MILESTONES = [
  epoch("2018-02-08 08:00:00.0+1:00"), 88000000000000, // 12 % discount
  epoch("2018-02-10 08:00:00.0+1:00"), 92000000000000, //  8 % discount
  epoch("2018-02-17 08:00:00.0+1:00"), 96000000000000, //  4 % discount
  epoch("2018-02-24 08:00:00.0+1:00"), 100000000000000, //  0 % discount
  epoch("2018-03-04 20:00:00.0+1:00"), 0, // signifies the end
]

const CX_CROWDSALE_START = CX_MILESTONES[0]
const CX_CROWDSALE_END   = CX_MILESTONES[CX_MILESTONES.length - 2]

const CX_MIN_FUNDING_GOAL = web3.toWei(2000, "ether")
const CX_MAX_FUNDING_GOAL = web3.toWei(7000, "ether")


const CX_TEAM_TOKENS_AS_PERCENT_OF_TOTAL = 5384 // Calculated as (0.35/0.65)*10000 and rounded to int - see BonusFinalizeAgent

function epoch(dateStr) {
  return (new Date(dateStr)).getTime()/1000
}

module.exports = deployer => {
  var crowdsaleToken

  deployer.deploy(SafeMathLib)
  deployer.link(SafeMathLib, [CrowdsaleToken, MilestonePricing, CargoXCrowdsale, BonusFinalizeAgent])

  deployer.deploy([
    [MultiSigWallet, CX_MULTISIG_WALLET_OWNERS, CX_MULTISIG_WALLET_REQ_SIG],
    [CrowdsaleToken, CX_TOKEN_NAME, CX_TOKEN_SYMBOL, CX_TOKEN_INITIAL_SUPPLY, CX_TOKEN_DECIMALS, true],
    [MilestonePricing, CX_MILESTONES]
  ])
  .then(() => {

    return deployer.deploy(CargoXCrowdsale,
      CrowdsaleToken.address,
      MilestonePricing.address,
      MultiSigWallet.address,
      CX_CROWDSALE_START,
      CX_CROWDSALE_END,
      CX_MIN_FUNDING_GOAL,
      CX_MAX_FUNDING_GOAL).then()
  })
  .then(() => {

    return deployer.deploy(BonusFinalizeAgent,
      CrowdsaleToken.address,
      CargoXCrowdsale.address,
      CX_TEAM_TOKENS_AS_PERCENT_OF_TOTAL,
      MultiSigWallet.address).then()
  })
  .then(() => {
    return CrowdsaleToken.deployed()
  })
  .then((instance) => {
    crowdsaleToken = instance
    /* set CargoXCrowdsale as minting agent */
    return crowdsaleToken.setMintAgent(CargoXCrowdsale.address, true).then()
  })
  .then(() => {
    /* set BonusFinalizeAgent as minting agent */
    return crowdsaleToken.setMintAgent(BonusFinalizeAgent.address, true).then()
  })
  .then(() => {
    /* set BonusFinalizeAgent as release agent */
    return crowdsaleToken.setReleaseAgent(BonusFinalizeAgent.address).then()
  })
  .then(() => {
    return CargoXCrowdsale.deployed()
  })
  .then((instance) => {
    /* set BonusFinalizeAgent as finalize agent on CargoXCrowdsale */
    return instance.setFinalizeAgent(BonusFinalizeAgent.address).then()
  })
  .then(() => {
    console.log("\n\nSuccesfully setup CargoX TGE.")

    console.log(
      "-- CrowdsaleToken: " + CrowdsaleToken.address + "\n" +
      "-- CargoXCrowdsale: " + CargoXCrowdsale.address + "\n" +
      "\n"
    )
  })
}
